name: CI

on:
  push:
    tags:
      - "v*"      # kjør release når du pusher en tag (eks: v1.2.3)
    branches:
      - "**"      # behold push-build på alle branches
  pull_request:

permissions:
  contents: read   # default for hele workflowen; justeres på release-jobben

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pytest
      - name: Run tests
        run: |
          pytest || if [ $? -eq 5 ]; then echo "No tests collected"; else exit $?; fi

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python -m build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    # KUN når vi pusher tag (fra on.push.tags over)
    permissions:
      contents: write   # <- må til for å lage release med GITHUB_TOKEN
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # (valgfritt) sjekk hva som faktisk ble lastet ned
      - name: List artifacts
        run: ls -al dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
